# Generated by Django 5.2.17 on 2026-10-02 17:50

import django.db.models.functions.text
from django.db import migrations, models


def canonicalize_existing_emails(apps, schema_editor):
    user_model = apps.get_model("accounts", "User")
    users = list(user_model.objects.only("id", "email").order_by("id"))
    canonical_owners = {}

    for user in users:
        canonical_email = user.email.strip().lower()
        existing_owner = canonical_owners.get(canonical_email)
        if existing_owner is not None:
            raise RuntimeError(
                "Cannot canonicalize accounts.User emails because users "
                f"{existing_owner} and {user.pk} share {canonical_email!r}"
            )
        canonical_owners[canonical_email] = user.pk
        user.email = canonical_email

    if users:
        user_model.objects.bulk_update(users, ["email"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(canonicalize_existing_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("email", django.db.models.functions.text.Lower("email"))),
                name="accounts_user_email_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="accounts_user_email_ci_unique",
            ),
        ),
    ]
