# Generated by Django 5.2.17 on 2026-10-04 09:20

import uuid

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_email_verified_at_accountsecurityevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthEmailOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("invitation", "Invitation"),
                            ("verification", "Verification"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=32,
                    ),
                ),
                ("deduplication_key", models.CharField(max_length=128, unique=True)),
                ("recipient", models.EmailField(blank=True, max_length=254)),
                ("recipient_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "available_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("locked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="InvitationEmailLock",
            fields=[
                ("email", models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="invitation",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accepted_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("email", django.db.models.functions.text.Lower("email"))),
                name="accounts_invitation_email_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("accepted_at__isnull", True), ("revoked_at__isnull", True)),
                name="accounts_invitation_one_pending_email",
            ),
        ),
        migrations.AddField(
            model_name="authemailoutbox",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_jobs",
                to="accounts.invitation",
            ),
        ),
        migrations.AddField(
            model_name="authemailoutbox",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authemailoutbox",
            name="verification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="email_jobs",
                to="accounts.emailverificationtoken",
            ),
        ),
        migrations.AddIndex(
            model_name="authemailoutbox",
            index=models.Index(
                fields=["sent_at", "failed_at", "available_at"], name="accounts_email_pending_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="authemailoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sent_at__isnull", True), ("failed_at__isnull", True), _connector="OR"
                ),
                name="accounts_email_not_sent_failed",
            ),
        ),
        migrations.AddConstraint(
            model_name="authemailoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("invitation__isnull", False),
                        ("kind", "invitation"),
                        ("user__isnull", True),
                        ("verification__isnull", True),
                    ),
                    models.Q(
                        ("invitation__isnull", True),
                        ("kind", "verification"),
                        ("user__isnull", False),
                        ("verification__isnull", False),
                    ),
                    models.Q(
                        ("invitation__isnull", True),
                        ("kind", "password_reset"),
                        ("verification__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="accounts_email_target_matches_kind",
            ),
        ),
    ]
