# Generated by Django 5.2.17 on 2026-10-04 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_authemailoutbox_invitationemaillock_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountsecurityevent",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ("-created_at",),
            },
        ),
    ]
