# Generated by Django 5.2.17 on 2026-10-04 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_accountsecurityevent_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountsecurityevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="security_events_as_actor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="accountsecurityevent",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="security_events_as_target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
