# Generated by Django 5.2.17 on 2026-10-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_accountsecurityevent_actor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authemailoutbox",
            name="credential_state_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
