# Generated by Django 5.2.17 on 2026-10-05 09:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="", max_length=5000)),
                (
                    "investment_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("KZT", "Kzt"), ("USD", "Usd"), ("EUR", "Eur")],
                        default="KZT",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active")],
                        default="draft",
                        max_length=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-created_at"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("investment_amount__isnull", True),
                            ("investment_amount__gt", 0),
                            _connector="OR",
                        ),
                        name="projects_project_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency__in", ("KZT", "USD", "EUR"))),
                        name="projects_project_currency_supported",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("activated_at__isnull", True), ("status", "draft")),
                            models.Q(("activated_at__isnull", False), ("status", "active")),
                            _connector="OR",
                        ),
                        name="projects_project_status_activation_consistent",
                    ),
                ],
            },
        ),
    ]
